### ISSUE TITLE
Dodgy example of params in the spec

### ISSUE THREAD

**Issue by croyzor** [CQCL-DEV/hugr#311]
In our YAML resource examples in the spec we have this example
```
- name: GraphOp
    description: "Involves running an argument Graph. E.g. run it some variable number of times."
    params:
      - r: ResourceSet
    signature:
      inputs: [[null, Graph[r](Int -> Int)], ["arg", Int]]
      outputs: [[null, Int]]
      resources: r # Indicates that running this operation also invokes resources r
    lowering:
      file: "graph_op_hugr.bin"
      resources: ["arithmetic", r] # r is the ResourceSet in "params"
```
but our grammer of parameter types is
```
TypeParam ::= "Type" | "ClassicType" | Int | "List"(TypeParam)
```
so `ResourceSet` shouldn't be allowed as a parameter. This leaves the only way to write this operation as
```
params: [["G", Type]]
inputs: [[null, G], ["arg", Int]]
```
which isn't ideal
